name: Ethereum Gas Estimator

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - next
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "4.14.1"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install opam packages
        run:
          opam install . --deps-only --with-doc --with-test -y

      - name: Run build
        run: opam exec -- make

      - name: Lint OCaml files
        run: opam exec -- make lint
