name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - next

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.14.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-${{ hashFiles('gas_estimator.opam') }}
          restore-keys: |
            v1-${{ runner.os }}-opam-${{ matrix.ocaml-version }}-

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Install system packages required by opam packages
        run: opam depext --yes --update geoip ocurl tls

      - name: Install opam packages
        if: steps.cache-opam.outputs.cache-hit != 'true'
        run: |
          opam install . --deps-only --with-doc --with-test -y

      - name: Check the consistency of installed opam packages
        if: steps.cache-opam.outputs.cache-hit == 'true'
        run: opam upgrade --fixup

      - name: Run build
        run: opam exec -- make
